// Code generated by mockery. DO NOT EDIT.

package repository

import (
	io "io"

	models "github.com/kumojin/go-blob-repository/models"
	mock "github.com/stretchr/testify/mock"
)

// BlobRepository is an autogenerated mock type for the BlobRepository type
type BlobRepository struct {
	mock.Mock
}

// Upload provides a mock function with given fields: metadata, in
func (_m *BlobRepository) Upload(metadata models.BlobMetadata, in io.Reader) (*models.UploadURL, error) {
	ret := _m.Called(metadata, in)

	var r0 *models.UploadURL
	if rf, ok := ret.Get(0).(func(models.BlobMetadata, io.Reader) *models.UploadURL); ok {
		r0 = rf(metadata, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UploadURL)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.BlobMetadata, io.Reader) error); ok {
		r1 = rf(metadata, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
