name: golangci-lint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  GOLANGCI_LINT_VERSION: "v1.64.4"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: '1.21'
          cache: false

      - name: Run vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@e0ebdd245eea59746bb0b28ea6a9871d3e35fbc9 # v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout 3m --enable=gofmt --verbose
